/*******************************************************************************
 *  CodeShelf
 *  Copyright (c) 2005-2012, Jeffrey B. Williams, All rights reserved
 *  $Id: WsRespCmdABC.java,v 1.1 2013/03/17 19:19:12 jeffw Exp $
 *******************************************************************************/
package com.gadgetworks.codeshelf.ws.command.resp;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;

/**
 * @author jeffw
 *
 */
public abstract class WsRespCmdABC implements IWsRespCmd {

	private String		mCommandId;
	private JsonNode	mDataJsonNode;
	protected ObjectNode	mResponseNode;

	public WsRespCmdABC() {

	}

	/**
	 * @param inCommandId
	 * @param inDataAsJson
	 */
	public WsRespCmdABC(final String inCommandId, final JsonNode inDataAsJson) {

		mCommandId = inCommandId;
		mDataJsonNode = inDataAsJson;
	}

	public boolean isError() {
		if (mResponseNode != null) {
			return mResponseNode.findPath(STATUS_ELEMENT).asText().equals("ERROR");
		}
		else {
			return false;
		}
	}
	
	protected abstract void doPrepareDataNode(ObjectNode inOutDataNode);

	public final String getCommandId() {
		return mCommandId;
	}

	public final void setCommandId(String inCommandId) {
		mCommandId = inCommandId;
	}

	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	public final String toString() {
		String result = "Command Id: " + mCommandId + " Data: " + mDataJsonNode;
		return result;
	}

	public final ObjectNode getResponseNode() {
		// Construct the response node from the data node generated by the subclass.
		ObjectMapper treeMapper = new ObjectMapper();
		ObjectNode objectNode = treeMapper.createObjectNode();
		objectNode.put(COMMAND_ID_ELEMENT, getCommandId());
		objectNode.put(COMMAND_TYPE_ELEMENT, getCommandEnum().getName());
		
		// Create and populate the data node.
		ObjectNode dataNode = objectNode.putObject(DATA_ELEMENT);
		doPrepareDataNode(dataNode);
		return objectNode;
	}
	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see com.gadgetworks.codeshelf.web.websession.command.IWebSessionCommand#serialize()
	 */
	public final String getResponseMsg() {
		return getResponseNode().toString();
	}
}
