/*******************************************************************************
 *  CodeShelf
 *  Copyright (c) 2005-2011, Jeffrey B. Williams, All rights reserved
 *  $Id: WebSessionCmdABC.java,v 1.1 2012/02/24 07:41:23 jeffw Exp $
 *******************************************************************************/
package com.gadgetworks.codeshelf.web.websession.command;

import org.codehaus.jackson.JsonNode;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.node.ObjectNode;

/**
 * @author jeffw
 *
 */
public abstract class WebSessionCmdABC implements IWebSessionCmd {

	private String		mCommandId;
	private JsonNode	mDataJsonNode;

	public WebSessionCmdABC() {

	}

	/**
	 * @param inCommandId
	 * @param inDataAsJson
	 */
	public WebSessionCmdABC(final String inCommandId, final JsonNode inDataAsJson) {

		mCommandId = inCommandId;
		mDataJsonNode = inDataAsJson;
	}

	// The subclasses execute the command and return a command data reesponse.
	protected abstract IWebSessionCmd doExec();

	protected abstract void prepareDataNode(ObjectNode inOutDataNode);

	public final String getCommandId() {
		return mCommandId;
	}

	public final void setCommandId(String inCommandId) {
		mCommandId = inCommandId;
	}

	public final JsonNode getDataJsonNode() {
		return mDataJsonNode;
	}

	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see com.gadgetworks.codeshelf.web.websession.command.IWebSessionCommand#exec()
	 */
	public final IWebSessionCmd receive() {
		IWebSessionCmd result = null;

		result = doExec();

		if (result != null) {
			result.setCommandId(this.getCommandId());
		}

		return result;
	}

	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see com.gadgetworks.codeshelf.web.websession.command.IWebSessionCommand#serialize()
	 */
	public final String prepareToSend() {

		// Construct the response node from the data node generated by the subclass.
		ObjectMapper treeMapper = new ObjectMapper();
		ObjectNode objectNode = treeMapper.createObjectNode();
		objectNode.put(COMMAND_ID_ELEMENT, getCommandId());
		objectNode.put(COMMAND_TYPE_ELEMENT, getCommandEnum().getName());

		// Create and populate the data node.
		ObjectNode dataNode = objectNode.putObject(DATA_ELEMENT);
		prepareDataNode(dataNode);

		return objectNode.toString();
	}
}
