/*******************************************************************************
 *  CodeShelf
 *  Copyright (c) 2005-2011, Jeffrey B. Williams, All rights reserved
 *  $Id: WebSessionCommandABC.java,v 1.2 2012/02/21 02:45:11 jeffw Exp $
 *******************************************************************************/
package com.gadgetworks.codeshelf.web.websession.command;

import org.codehaus.jackson.JsonNode;
import org.codehaus.jackson.map.ObjectMapper;
import org.codehaus.jackson.node.ObjectNode;

/**
 * @author jeffw
 *
 */
public abstract class WebSessionCommandABC implements IWebSessionCommand {

	private String		mCommandId;
	private JsonNode	mDataJsonNode;
	
	public WebSessionCommandABC(final JsonNode inCommandAsJson) {
		JsonNode commandIdNode = inCommandAsJson.get(COMMAND_ID_ELEMENT);
		mCommandId = commandIdNode.asText();

		mDataJsonNode = inCommandAsJson.get(IWebSessionCommand.DATA_ELEMENT);
	}

	// The subclasses execute the command and return a command data reesponse.
	protected abstract IWebSessionCommand doExec();

	public final String getCommandId() {
		return mCommandId;
	}

	public final JsonNode getDataJsonNode() {
		return mDataJsonNode;
	}

	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see com.gadgetworks.codeshelf.web.websession.command.IWebSessionCommand#exec()
	 */
	public final IWebSessionCommand exec() {
		IWebSessionCommand result = null;
		
		result = doExec();

		// Construct the response node from the data node generated by the subclass.
		ObjectMapper treeMapper = new ObjectMapper();
		ObjectNode objectNode = treeMapper.createObjectNode();
		objectNode.put(COMMAND_ID_ELEMENT, getCommandId());
		objectNode.put(COMMAND_TYPE_ELEMENT, getCommandEnum().getName());
		ObjectNode dataNode = objectNode.putObject(DATA_ELEMENT);
		dataNode.putAll((ObjectNode) commandDataNode);

		result = objectNode;

		return result;
	}

	// --------------------------------------------------------------------------
	/* (non-Javadoc)
	 * @see com.gadgetworks.codeshelf.web.websession.command.IWebSessionCommand#serialize()
	 */
	public final String serialize() {
		return "";
	}
}
